from __future__ import annotations

from decimal import Decimal


DEFAULT_ARBITRAGE_NOTIONAL_USD = 1000.0
DEFAULT_ARBITRAGE_BASKET_SIZE = 2
DEFAULT_ARBITRAGE_TRADE_FEE_PERCENT = 0.10
DEFAULT_ARBITRAGE_FLASHLOAN_FEE_PERCENT = 0.05
DEFAULT_ARBITRAGE_FEE_RESERVE_PERCENT = 0.10
DEFAULT_ARBITRAGE_MIN_WINDOW_SPREAD_PERCENT = 0.30
DEFAULT_ARBITRAGE_MIN_PAPER_PROFIT_USD = 0.0
DEFAULT_ARBITRAGE_TARGET_PROFIT_PERCENT = 0.618
DEFAULT_ARBITRAGE_ROUTE_TRADE_FEE_HOPS = 3
DEFAULT_EXECUTION_SLIPPAGE_BPS = 50
DEFAULT_EXECUTION_PLAN_MAX_AGE_SECONDS = 15
DEFAULT_BINANCE_CHANGE_WINDOW_SECONDS = 1.0
DEFAULT_BINANCE_VELOCITY_MIN_CHANGE_PERCENT = 0.2
DEFAULT_BINANCE_RAW_SIDE_LIMIT = 50

DEFAULT_MIN_COW_SPREAD_PERCENT = 0.0
DEFAULT_MIN_SIDE_CHANGE_PERCENT = 0.05
DEFAULT_MIN_COW_SIDE_CHANGE_PERCENT = 0.30
DEFAULT_TRIGGER_MIN_UP_CHANGE_PERCENT = DEFAULT_MIN_SIDE_CHANGE_PERCENT
DEFAULT_TRIGGER_MIN_DOWN_CHANGE_PERCENT = DEFAULT_MIN_SIDE_CHANGE_PERCENT
DEFAULT_MIN_TOKEN_PRICE_USD = 0.01
DEFAULT_COW_NETWORK_DISPLAY_LIMIT = 5
DEFAULT_COW_AUTO_EXECUTE_MIN_PROFIT_PERCENT = Decimal(str(DEFAULT_ARBITRAGE_TARGET_PROFIT_PERCENT))
DEFAULT_COW_TRADE_FEE_SIDE_COUNT = 2


def strategy_defaults() -> dict[str, float | int]:
    return {
        "ARBITRAGE_NOTIONAL_USD": DEFAULT_ARBITRAGE_NOTIONAL_USD,
        "ARBITRAGE_BASKET_SIZE": DEFAULT_ARBITRAGE_BASKET_SIZE,
        "ARBITRAGE_TRADE_FEE_PERCENT": DEFAULT_ARBITRAGE_TRADE_FEE_PERCENT,
        "ARBITRAGE_FLASHLOAN_FEE_PERCENT": DEFAULT_ARBITRAGE_FLASHLOAN_FEE_PERCENT,
        "ARBITRAGE_FEE_RESERVE_PERCENT": DEFAULT_ARBITRAGE_FEE_RESERVE_PERCENT,
        "ARBITRAGE_MIN_WINDOW_SPREAD_PERCENT": DEFAULT_ARBITRAGE_MIN_WINDOW_SPREAD_PERCENT,
        "ARBITRAGE_MIN_PAPER_PROFIT_USD": DEFAULT_ARBITRAGE_MIN_PAPER_PROFIT_USD,
        "ARBITRAGE_TARGET_PROFIT_PERCENT": DEFAULT_ARBITRAGE_TARGET_PROFIT_PERCENT,
        "ARBITRAGE_ROUTE_TRADE_FEE_HOPS": DEFAULT_ARBITRAGE_ROUTE_TRADE_FEE_HOPS,
        "EXECUTION_SLIPPAGE_BPS": DEFAULT_EXECUTION_SLIPPAGE_BPS,
        "EXECUTION_PLAN_MAX_AGE_SECONDS": DEFAULT_EXECUTION_PLAN_MAX_AGE_SECONDS,
        "BINANCE_CHANGE_WINDOW_SECONDS": DEFAULT_BINANCE_CHANGE_WINDOW_SECONDS,
        "BINANCE_VELOCITY_MIN_CHANGE_PERCENT": DEFAULT_BINANCE_VELOCITY_MIN_CHANGE_PERCENT,
        "TRIGGER_MIN_UP_CHANGE_PERCENT": DEFAULT_TRIGGER_MIN_UP_CHANGE_PERCENT,
        "TRIGGER_MIN_DOWN_CHANGE_PERCENT": DEFAULT_TRIGGER_MIN_DOWN_CHANGE_PERCENT,
    }


def calculate_min_paper_profit_usd(notional_usd: float, target_profit_percent: float = DEFAULT_ARBITRAGE_TARGET_PROFIT_PERCENT) -> float:
    return max(0.0, float(notional_usd)) * max(0.0, float(target_profit_percent)) / 100.0


def normalize_min_paper_profit_usd(value: float) -> float:
    return max(0.0, float(value))


def resolve_min_paper_profit_usd(
    configured_min_profit_usd: float,
    *,
    notional_usd: float,
    target_profit_percent: float = DEFAULT_ARBITRAGE_TARGET_PROFIT_PERCENT,
) -> float:
    configured = normalize_min_paper_profit_usd(configured_min_profit_usd)
    if configured > 0:
        return configured
    return calculate_min_paper_profit_usd(notional_usd, target_profit_percent)
